version: "3.9"

networks:
  megamolbart_net:
    name: megamolbart_net
    driver: bridge

services:
  megamolbart:
    image: nvcr.io/nv-drug-discovery-dev/megamolbart:latest
    networks:
      - megamolbart_net
    expose:
      - "50051"
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /opt/nvidia/cheminfomatics/megamolbart
    command: python3 -m megamolbart
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]

  nginx:
    image: nginx:1.20.0
    container_name: load_balancer
    ports:
      - "50052:50052"
    depends_on:
      - megamolbart
    networks:
      - megamolbart_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
